name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Eslint
        run: yarn run lint
      - name: Build
        run: yarn run build
